### PR TITLE
Make a few improvements

### PR DESCRIPTION
**Pull request by git-bruh**
Makes a few changes like adding bold text, using a generic way to get the CPU name, using a Makefile and also adds a screenshot to the README.

### CODE REVIEW

**Comment by Mati232411** [comment]
Thanks can i copy it to my repo?

**Comment by Mati232411** [comment]
Thanks for help

**Comment by git-bruh** [comment]
No problem :+1: 
Also, you might wanna add an updated screenshot to your own repo, and update the link in the readme. Do `chmod +x bfetch` before uploading the file to github so that it's executable when installed via the Makefile. Not sure if this can be done through the web interface though and also update the Makefile according to whatever logos you add so that they're installed into /etc/bfetch

**Comment by Mati232411** [comment]
Ok thanks

**Pull request merged**
